### ISSUE TITLE
Can i run this on windows?

### ISSUE THREAD

**Issue by sanishan** [mattcollier/noxious#24]
I have try to setup this on Windows, but I am getting this error message:

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: spawn tor ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

[OK]

Thanks,

**Comment by mattcollier** [comment]
@sanishan I'm afraid I don't have any information about running on Windows.  

I just attempted to do a fresh install on Linux and there are some different failures.  There may be some changes needed to work with more recent versions of Electron.  I won't be able to look into fixing things any time soon.  PRs welcome.
